vars:
  ROBOT_VARIANT: kyon02
  ACTION_REPEAT: 5
  COMMENT: kyon02 no wheels CLOSED partial, UTD 8, action rep 5, target entropy -0.5, fake pos track max 1.0 m/s (action rate, NO CoT, dir track, 1.0 omega weight
  ENV_IDX_BAG: 5
  N_ENVS: 800
  RNAME: Kyon02PartialCloopNoWheels
  SEED: 34
  SHM_NS: kyon02_no_wheels
  TOT_STEPS: 14000000
  TRAIN_ENV_CNAME: FakePosTrackingEnv
  TRAIN_ENV_FNAME: fake_pos_tracking_env
custom_args:
  robot_description:
    wheels:
      dtype: xacro
      value: false
    base_linkname:
      dtype: str
      value: pelvis
    self_collide:
      dtype: bool
      value: false
  control:
    fixed_flights:
      dtype: bool
      value: true
    adaptive_is:
      dtype: bool
      value: true
    lin_a_feedback:
      dtype: bool
      value: false
    closed_partial:
      dtype: bool
      value: true
    estimate_v_root:
      dtype: bool
      value: false
    use_jnt_v_feedback:
      dtype: bool
      value: true
    step_height:
      dtype: float
      value: 0.12
  world_interface:
    use_flat_ground:
      dtype: bool
      value: true
