vars:
  ROBOT_VARIANT: talos_perception
  ACTION_REPEAT: 3
  COMMENT: talos closed-loop partial on non-flat terrain with heightmap observations
  ENV_IDX_BAG: 0
  N_ENVS: 1
  PUB_HEIGHTMAP: 1
  REMOTE_STEPPING: 1
  RNAME: TalosPerception
  SEED: 7383
  SHM_NS: talos
  TIMEOUT_MS: 300000
  TOT_STEPS: 15000000
  TRAIN_ENV_CNAME: FakePosTrackEnvPhaseControl
  TRAIN_ENV_FNAME: fake_pos_track_env_phase_control
custom_args:
  robot_description:
    foot_collision:
      dtype: xacro
      value: thinbox
    head_type:
      dtype: xacro
      value: default
    flexibility:
      dtype: xacro
      value: false
    use_fixed_base:
      dtype: xacro
      value: false
    use_sim:
      dtype: xacro
      value: true
    enable_crane:
      dtype: xacro
      value: false
    disable_gazebo_camera:
      dtype: xacro
      value: true
    use_capsule_collision:
      dtype: xacro
      value: false
    multiple:
      dtype: xacro
      value: false
    gazebo_version:
      dtype: xacro
      value: classic
    add_upper_body:
      dtype: bool
      value: true
    self_collide:
      dtype: bool
      value: true
    minimal_coll:
      dtype: xacro
      value: true
  control:
    adaptive_is:
      dtype: bool
      value: true
    closed_partial:
      dtype: bool
      value: true
    fixed_flights:
      dtype: bool
      value: true
    fully_closed:
      dtype: bool
      value: false
    estimate_v_root:
      dtype: bool
      value: false
    lin_a_feedback:
      dtype: bool
      value: false
    use_jnt_v_feedback:
      dtype: bool
      value: false
    step_height:
      dtype: float
      value: 0.1
    initial_force_load_divisor:
      dtype: float
      value: 1.12
  world_interface:
    rendering_dt:
      dtype: float
      value: 0.1
    use_flat_ground:
      dtype: bool
      value: false
    spawning_height:
      dtype: float
      value: 1.12
    ground_type:
      dtype: str
      value: stepup_prim
    use_random_pertub:
      dtype: bool
      value: false
  perception:
    enable_height_sensor:
      dtype: bool
      value: true
    height_sensor_pixels:
      dtype: int
      value: 10
    height_sensor_resolution:
      dtype: float
      value: 0.16
    enable_height_vis:
      dtype: bool
      value: false
    height_sensor_forward_offset:
      dtype: float
      value: 0.0
    height_sensor_lateral_offset:
      dtype: float
      value: 0.0
