vars:
  ROBOT_VARIANT: centauro_cloop
  ACTION_REPEAT: 4
  COMMENT: centauro big wheels CLOSED, action rep 4, gamma 0.98, UTD 8, joint pof0 fix (5%), huge bsize, fake pos track (action rate, CoT, dir track, max_vref 1.0 m/s, max omega 0.4 rad/s,), trgt entropy -0.5
  ENV_IDX_BAG: 5
  N_ENVS: 800
  RNAME: CentauroCloopPartialNoWheels
  SEED: 383
  SHM_NS: centauro_big_wheels
  TOT_STEPS: 15000000
  TRAIN_ENV_CNAME: FakePosTrackingEnv
  TRAIN_ENV_FNAME: fake_pos_tracking_env
custom_args:
  control:
    use_jnt_v_feedback:
      dtype: bool
      value: true
    control_wheels:
      dtype: bool
      value: false
    fixed_flights:
      dtype: bool
      value: true
    adaptive_is:
      dtype: bool
      value: true
    lin_a_feedback:
      dtype: bool
      value: false
    closed_partial:
      dtype: bool
      value: true
    estimate_v_root:
      dtype: bool
      value: false
    step_height:
      dtype: float
      value: 0.1
  world_interface:
    rendering_dt:
      dtype: float
      value: 0.1
    use_flat_ground:
      dtype: bool
      value: true
    ground_type:
      dtype: str
      value: random_patches
    dh_ground:
      dtype: float
      value: 0.02
  robot_description:
    add_upper_body:
      dtype: bool
      value: false
