vars:
  ROBOT_VARIANT: centauro_ub_cloop_pert_recovery
  ACTION_REPEAT: 4
  COMMENT: centauro big wheels CLOSED pert recovery, even stronger perturbations with fixed freq, mostly omega tracking, full flight control (also neg), entropy annhealing, bsize 16394, utd 2
  ENV_IDX_BAG: 78
  N_ENVS: 800
  OVERRIDE_AGENT_REFS: ''
  OVERRIDE_ENV: 0
  PUB_HEIGHTMAP: 1
  RNAME: CentauroCloopPartialUbNoWheelsPertRecovery
  SEED: 7987
  SHM_NS: centauro_big_wheels_ub
  TOT_STEPS: 12000000
  TRAIN_ENV_CNAME: StayingAliveEnv
  TRAIN_ENV_FNAME: derived.staying_alive_env
custom_args:
  world_interface:
    rendering_dt:
      dtype: float
      value: 0.1
    use_flat_ground:
      dtype: bool
      value: true
    ground_type:
      dtype: str
      value: stepup_prim
    use_random_pertub:
      dtype: bool
      value: true
  perception:
    enable_height_sensor:
      dtype: bool
      value: false
    height_sensor_pixels:
      dtype: int
      value: 10
    height_sensor_resolution:
      dtype: float
      value: 0.16
    enable_height_vis:
      dtype: bool
      value: false
  control:
    use_jnt_v_feedback:
      dtype: bool
      value: true
    control_wheels:
      dtype: bool
      value: false
    fixed_flights:
      dtype: bool
      value: true
    adaptive_is:
      dtype: bool
      value: true
    lin_a_feedback:
      dtype: bool
      value: false
    closed_partial:
      dtype: bool
      value: true
    estimate_v_root:
      dtype: bool
      value: false
    step_height:
      dtype: float
      value: 0.1
  robot_description:
    fix_yaw:
      dtype: bool
      value: true
    self_collide:
      dtype: bool
      value: false
    add_upper_body:
      dtype: bool
      value: true
