vars:
  ROBOT_VARIANT: centauro_ub_open
  ACTION_REPEAT: 3
  COMMENT: centauro big wheels with upper body OPEN LOOP,ow using same jnt imp config as robot, action rep 3, gamma 0.98, UTD 4, no entropy annhealing, fake pos track (action rate, CoT, dir track, max_vref 1.0 m/s, max omega 0.4 rad/s,)
  ENV_IDX_BAG: 478
  N_ENVS: 800
  RNAME: CentauroOpenUbNoWheels
  SEED: 92
  SHM_NS: centauro_big_wheels_ub_open
  TOT_STEPS: 15000000
  TRAIN_ENV_CNAME: FakePosTrackingEnv
  TRAIN_ENV_FNAME: fake_pos_tracking_env
custom_args:
  training:
    use_random_pertub:
      dtype: bool
      value: true
    step_height:
      dtype: float
      value: 0.1
  control:
    use_jnt_v_feedback:
      dtype: bool
      value: false
    control_wheels:
      dtype: bool
      value: false
    fixed_flights:
      dtype: bool
      value: true
    adaptive_is:
      dtype: bool
      value: true
    lin_a_feedback:
      dtype: bool
      value: false
    closed_partial:
      dtype: bool
      value: true
    estimate_v_root:
      dtype: bool
      value: false
  world_interface:
    use_flat_ground:
      dtype: bool
      value: true
  robot_description:
    add_upper_body:
      dtype: bool
      value: true
