vars:
  ROBOT_VARIANT: centauro_no_yaw_ub_cloop_perception
  ACTION_REPEAT: 3
  COMMENT: centauro big wheels (fixed ankle yaw) with upper body CLOOP, 16392 bsize, UTD 4, forward offset to heighmap, NO entropy annhealing [-0.2, -0.5], 8-15cm steps, 25 steps, 0.4/1.5 m width, flight control (apex 0.35, end[+-] 0.2/0, length (min 8), NO landing control), CoT 0.3 scale 0.3 offset, 1.0 forwrad tracking, 0.2 yaw rate directional no yaw rand
  DUMP_DT: 30.0
  DUMP_ENV_CHECKPOINTS: 0
  ENV_IDX_BAG: 79
  MNAME: d2026_01_19_h14_m54_s32-CentauroCloopPartialNoYawUbPercep_FakePosTrackEnvPhaseControl_model
  MPATH: /root/training_data/AugMPCModels/bundles/centauro/d2026_01_19_h14_m54_s32-CentauroCloopPartialNoYawUbPercep_FakePosTrackEnvPhaseControl
  N_ENVS: 800
  OVERRIDE_ENV: 0
  PUB_HEIGHTMAP: 1
  RNAME: CentauroCloopPartialNoYawUbPercep
  SEED: 11
  SHM_NS: centauro_big_wheels_no_yaw_ub
  TOT_STEPS: 30000000
  TRAIN_ENV_CNAME: FakePosTrackEnvPhaseControl
  TRAIN_ENV_FNAME: fake_pos_track_env_phase_control
custom_args:
  world_interface:
    rendering_dt:
      dtype: float
      value: 0.05
    use_flat_ground:
      dtype: bool
      value: false
    ground_type:
      dtype: str
      value: stepup_prim
  perception:
    enable_height_sensor:
      dtype: bool
      value: true
    height_sensor_pixels:
      dtype: float
      value: 10
    height_sensor_resolution:
      dtype: float
      value: 0.16
    enable_height_vis:
      dtype: bool
      value: false
    height_sensor_forward_offset:
      dtype: float
      value: 0.2
    height_sensor_lateral_offset:
      dtype: float
      value: 0.0
  training:
    use_random_pertub:
      dtype: bool
      value: false
    step_height:
      dtype: float
      value: 0.1
  control:
    use_jnt_v_feedback:
      dtype: bool
      value: true
    control_wheels:
      dtype: bool
      value: true
    fixed_flights:
      dtype: bool
      value: true
    adaptive_is:
      dtype: bool
      value: true
    lin_a_feedback:
      dtype: bool
      value: false
    closed_partial:
      dtype: bool
      value: true
    estimate_v_root:
      dtype: bool
      value: false
  robot_description:
    fix_yaw:
      dtype: bool
      value: true
    self_collide:
      dtype: bool
      value: false
    add_upper_body:
      dtype: bool
      value: true
